purification:
  total_num_iterations: 200
  csgm_num_iterations: 100
  purification_schedule: linear
  save_every_main: 1000000
  save_every_sub: 1000000
  optimizer: SGD
  lr: 300
  momentum: 0.9
  ddim_num_iterations: 20
  full_ddim: True
  ddim_init_timestep: 1000
  ddim_end_timestep: 50
  use_weight_decay: False
  weight_decay_lambda: 0

dataset:
  name: ffhq
  root: ./data/ffhq

others:
  img_size: !!python/tuple [1,3,256,256]